BEGIN;

-- Catálogo real de tipos de O.S. do MK Solutions, obtido via
-- WSMKOSListaTiposOS.rule contra o MK de produção em 2026-09-18 (ver
-- docs/integracao-mk.md e AGENTS.md §6.4). Importado por completo — não só
-- os candidatos rurais — para já deixar o catálogo pronto para quando a
-- operação de fibra for configurada. Atribuir tipos a operações específicas
-- continua sendo uma ação manual via PUT /api/v1/operations/{id}/service-types,
-- não decidida por esta migração.
INSERT INTO mk_service_types (source, external_id, description, observed_at)
VALUES
  ('real', '64', 'AGUARDANDO', now()),
  ('real', '220', 'ATENDIMENTO PLANTÃO', now()),
  ('real', '200', 'ATUALIZAÇÃO DE CADASTRO', now()),
  ('real', '245', 'AUXILIO TECNICO', now()),
  ('real', '251', 'AVALIAÇÃO TÉCNICA', now()),
  ('real', '70', 'BAIXA DE EQUIPAMENTO', now()),
  ('real', '74', 'BAIXA PARA POP', now()),
  ('real', '202', 'BAIXA PARA SETOR ERIC', now()),
  ('real', '73', 'BAIXA PARA SETORES', now()),
  ('real', '140', 'BAIXA PARA SETOR ORTIZ', now()),
  ('real', '190', 'BAIXA PARA SETOR WILLIAN', now()),
  ('real', '82', 'BAIXA SETOR ADILSON', now()),
  ('real', '184', 'BAIXA SETOR BRUNO', now()),
  ('real', '203', 'BAIXA SETOR EVANDRO', now()),
  ('real', '85', 'BAIXA SETOR EWERTON', now()),
  ('real', '88', 'BAIXA SETOR JONATAN', now()),
  ('real', '191', 'BAIXA SETOR LANÇAMENTOS BAGÉ', now()),
  ('real', '83', 'BAIXA SETOR  LUCAS', now()),
  ('real', '86', 'BAIXA SETOR MARCO', now()),
  ('real', '84', 'BAIXA SETOR  MARIO', now()),
  ('real', '93', 'BAIXA SETOR RURAL', now()),
  ('real', '87', 'BAIXA SETOR TIAGO', now()),
  ('real', '241', 'CABO DE REDE', now()),
  ('real', '105', 'CANCELAMENTO', now()),
  ('real', '248', 'ENTREGA DE EQUIPAMENTO', now()),
  ('real', '94', 'ESTRUTURAÇÃO PRÉDIO + INSTALAÇÃO', now()),
  ('real', '214', 'ESTRUTURA PRÉDIO', now()),
  ('real', '206', 'ESTRUTURA PREDIO + TROCA DE ENDEREÇO', now()),
  ('real', '54', 'FTTH - AMPLIAÇÃO CTO', now()),
  ('real', '260', 'FTTH - AUXILIO REDE URGENTE', now()),
  ('real', '188', 'FTTH - CONFERÊNCIA', now()),
  ('real', '262', 'FTTH - CORREÇÃO DE SINAL', now()),
  ('real', '69', 'FTTH - FUSÃO ÓPTICA', now()),
  ('real', '52', 'FTTH - INSTALAÇÃO CTO', now()),
  ('real', '51', 'FTTH - LANÇAMENTO DE REDE', now()),
  ('real', '53', 'FTTH - MANUTENÇÃO', now()),
  ('real', '265', 'FTTH - PLANTÃO REDE', now()),
  ('real', '267', 'FTTH - POSTE LIMPO', now()),
  ('real', '187', 'FTTH - READEQUAÇÃO', now()),
  ('real', '186', 'FTTH - ROMPIMENTO DE ROTA', now()),
  ('real', '261', 'FTTH - URGÊNCIA AS', now()),
  ('real', '268', 'FTTH - URGÊNCIA DE REDE 4+', now()),
  ('real', '257', 'FTTH - URGÊNCIA REDE 4H', now()),
  ('real', '258', 'FTTH - URGÊNCIA REDE NOTURNA', now()),
  ('real', '236', 'GARANTIA DE SERVIÇO', now()),
  ('real', '25', 'INSTALAÇÃO FIBRA', now()),
  ('real', '239', 'INSTALAÇÃO FIBRA + ESTRUTURAÇÃO', now()),
  ('real', '34', 'INSTALAÇÃO FIBRA (SEM ROTEADOR)', now()),
  ('real', '2', 'INSTALAÇÃO RÁDIO', now()),
  ('real', '35', 'INSTALAÇÃO RÁDIO (SEM ROTEADOR)', now()),
  ('real', '29', 'INSTALAÇÃO RURAL', now()),
  ('real', '264', 'INSTALAÇÃO + TELEFONIA', now()),
  ('real', '207', 'LANÇAMENTO DE DROP', now()),
  ('real', '59', 'LANÇAMENTO FIBRA', now()),
  ('real', '215', 'LED LOSS', now()),
  ('real', '216', 'LUZ ALTA', now()),
  ('real', '40', 'MANUTENÇÃO - CATUÇABA', now()),
  ('real', '26', 'MANUTENÇÃO FIBRA', now()),
  ('real', '19', 'MANUTENÇÃO FIBRA POP', now()),
  ('real', '43', 'MANUTENÇÃO - IBARE', now()),
  ('real', '89', 'MANUTENÇÃO INTERNA', now()),
  ('real', '45', 'MANUTENÇÃO - LARANJEIRAS', now()),
  ('real', '42', 'MANUTENÇÃO - PALMA', now()),
  ('real', '24', 'MANUTENÇÃO - PREVENTIVA', now()),
  ('real', '253', 'MANUTENÇÃO PREVENTIVA PRÉDIO', now()),
  ('real', '222', 'MANUTENÇÃO PRIORIDADE', now()),
  ('real', '5', 'MANUTENÇÃO RÁDIO', now()),
  ('real', '249', 'MANUTENÇÃO RURAL POP', now()),
  ('real', '221', 'MANUTENÇÃO/SUPORTE EMPRESARIAL', now()),
  ('real', '41', 'MANUTENÇÃO - SUSPIRO', now()),
  ('real', '46', 'MANUTENÇÃO-TIARAJU', now()),
  ('real', '44', 'MANUTENÇÃO - VILANOVA', now()),
  ('real', '36', 'MIGRAÇÃO - INSTALAÇÃO', now()),
  ('real', '240', 'MONITORAMENTO PRÉDIO', now()),
  ('real', '199', 'ORÇAMENTO', now()),
  ('real', '63', 'OS PARA VOLTAR COMODATO', now()),
  ('real', '208', 'PLANTÃO DE DOMINGO', now()),
  ('real', '263', 'PLANTÃO DE EVENTOS', now()),
  ('real', '209', 'PLANTÃO DE FERIADO', now()),
  ('real', '255', 'PLANTÃO NOTURNO', now()),
  ('real', '223', 'PLANTÃO PRIORIDADE', now()),
  ('real', '229', 'QUALIFICAÇÃO DE OS', now()),
  ('real', '31', 'REATIVAÇÃO', now()),
  ('real', '252', 'REINCIDÊNCIA', now()),
  ('real', '65', 'RETIRADA DROP', now()),
  ('real', '227', 'RETIRADA - ERRO CONSULTOR COMERCIAL', now()),
  ('real', '12', 'RETIRADA FIBRA - CANCELADO', now()),
  ('real', '47', 'RETIRADA FIBRA - INADIMPLÊNCIA', now()),
  ('real', '114', 'RETIRADA FIBRA - TROCA DE ENDEREÇO', now()),
  ('real', '247', 'RETIRADA FIBRA - TROCA END LOCAL C CONEXAO', now()),
  ('real', '230', 'RETIRADA FINANCEIRO', now()),
  ('real', '196', 'RETIRADA - INSATISFAÇÃO', now()),
  ('real', '192', 'RETIRADA - MUDANÇA DE CIDADE', now()),
  ('real', '193', 'RETIRADA - NÃO RENOVADO', now()),
  ('real', '195', 'RETIRADA - ÓBITO', now()),
  ('real', '232', 'RETIRADA PEDIDO DE CANCELAMENTO', now()),
  ('real', '231', 'RETIRADA PERMUTA', now()),
  ('real', '233', 'RETIRADA PROBLEMAS DE SAÚDE', now()),
  ('real', '39', 'RETIRADA RÁDIO- CANCELADO', now()),
  ('real', '49', 'RETIRADA RÁDIO- INADIMPLÊNCIA', now()),
  ('real', '50', 'RETIRADA RÁDIO - TROCA DE ENDEREÇO', now()),
  ('real', '194', 'RETIRADA - SEM VIABILIDADE', now()),
  ('real', '219', 'RETIRADA TESTE SG', now()),
  ('real', '234', 'RETIRADA TROCA DE ENDEREÇO SEM VIABILIDADE', now()),
  ('real', '235', 'RETIRADA TROCA DE PROVEDOR', now()),
  ('real', '217', 'RETORNO ONU COMODATO', now()),
  ('real', '218', 'RETORNO ROTEADOR COMODATO', now()),
  ('real', '269', 'REVERSÃO', now()),
  ('real', '68', 'ROMPIMENTO DE DROP', now()),
  ('real', '204', 'ROMPIMENTO/ESTRUTURA', now()),
  ('real', '90', 'ROTEADOR SECUNDÁRIO', now()),
  ('real', '266', 'SATISFAÇÃO', now()),
  ('real', '242', 'SEM ACESSO', now()),
  ('real', '244', 'TESTE', now()),
  ('real', '4', 'TROCA DE ENDEREÇO - FIBRA', now()),
  ('real', '38', 'TROCA DE ENDEREÇO - RÁDIO', now()),
  ('real', '91', 'TROCA DE ROTEADOR AMPLIAÇÃO', now()),
  ('real', '92', 'TROCA DE ROTEADOR AMPLIAÇÃO+SECUNDÁRIO', now()),
  ('real', '238', 'TROCA DE ROTEADOR IPV6', now()),
  ('real', '254', 'VERIFICAÇÃO POP', now()),
  ('real', '67', 'VERIFICAR INSTALAÇÃO', now()),
  ('real', '20', 'VISADA', now()),
  ('real', '224', 'VISADA + INSTALAÇÃO', now()),
  ('real', '225', 'VISADA + INSTALAÇÃO RÁDIO', now()),
  ('real', '226', 'VISADA + INSTALAÇÃO RURAL', now()),
  ('real', '7', 'VISITA-TÉCNICA', now()),
  ('real', '30', 'VISITA TÉCNICA - RURAL', now())
ON CONFLICT (source, external_id) DO NOTHING;

COMMIT;
